annotations:
  artifacthub.io/license: Apache-2.0
  artifacthub.io/prerelease: "false"
apiVersion: v2
appVersion: v1.11.0
dependencies:
- condition: global.dex.enabled
  name: dex
  repository: https://charts.dexidp.io
  tags:
  - dex
  version: 0.15.2
- condition: minio.enabled, global.minio.enabled
  name: minio
  repository: https://charts.min.io/
  tags:
  - minio
  version: 5.0.13
- condition: kubed.enabled, global.kubed.enabled
  name: kubed
  repository: https://charts.appscode.com/stable/
  tags:
  - kubed
  version: v0.13.2
- condition: s3gw.enabled, global.s3gw.enabled
  name: s3gw
  repository: https://aquarist-labs.github.io/s3gw-charts
  tags:
  - s3gw
  version: 0.14.0
description: |
  Marsified version of epinio helm chart. Includes: 
  -> nodeSelectors to deployment yamls. 
  -> serviceAccount to epinio server.
  -> manage epinio server storage size thru values.yaml.

home: https://github.com/epinio/epinio
icon: https://raw.githubusercontent.com/epinio/helm-charts/main/assets/epinio.png
keywords:
- epinio
- paas
name: mars-epinio
sources:
- https://github.com/mars-platform-team/mars-epinio-helm-charts
version: 1.11.0
